### PR TITLE
TEST MINI cursror all pixel reduce 44 pixel

### PR DESCRIPTION
**Pull request by TukangM**
before releasing/merging it. can you make a gearlock package first so I can try it and find out which cursor is suitable

### CODE REVIEW

**Comment by SayaAEP** [comment]
ok umm. i pack with 7zip and i installed and yeah get error. seemslike old cursorpack old (with bootanimation) overwritten with github repo. and my bootanimation deleted

**Comment by Xtr126** [comment]
Here is a gxp file, it seems all fine. Rename it to .gxp if needed
[Cursor pack_1.1_Xtr.zip](https://github.com/Xtr126/CursorChangerGearlock/files/10042916/Cursor.pack_1.1_Xtr.zip)

**Comment by SayaAEP** [comment]
> 

ok i try tomorrow

**Comment by SayaAEP** [comment]
nice the cursor look smaller than default cursors

**Comment by SayaAEP** [comment]
image

... 
i wanted to make 3 different cursor "small, medium, large"
but right now maybe hmm not really used

**Comment by SayaAEP** [comment]
it ready

**Pull request merged**
